### ISSUE TITLE
`domainname` is not working for me in struct tags

### ISSUE THREAD

**Issue by jgoodall** [brianvoe/gofakeit#123]
The following struct results in `n/a` as the value for field `Domain`:

```
  Domain       string `fake:"{domainname}"`
```

**Comment by brianvoe** [comment]
Understandable the json tags will do a lookup from FuncLookup based upon added indexes. When i wrote the lookup functions I simplified it to domain instead of domainname. But i can see the confusion. So i changed the lookup index to domainname to be similar to the main function name. I pushed a release v5.10.1

Let me know if you come across any other inconsistencies and ill try to update it to reflect. Thanks.

**Comment by jgoodall** [comment]
Confirmed that this fixes the issue - thank you!
