### ISSUE TITLE
How I can generate date in range by tag?

### ISSUE THREAD

**Issue by scippio** [brianvoe/gofakeit#156]
Is possible generate datetime from daterange tag?

Like:
```
MyDate *time.Time `fake:"{daterange:[1970-01-01,2000-12-31]}"` ?
```

**Comment by scippio** [comment]
Nevermind... I created my own custom function:
```
fake:"{daterange2:[1970-01-01],[2000-12-31]}"
``` 

```
gofakeit.AddFuncLookup("daterange2", gofakeit.Info{
		Output:      "time.Time",
		Description: "Generate random time in range",
		Params: []gofakeit.Param{
			{
				Field:       "start",
				Type:        "string",
				Description: "Start range to select random date",
			},
			{
				Field:       "end",
				Type:        "string",
				Description: "End range to select random date",
			},
		},
		Generate: func(r *rand.Rand, m *gofakeit.MapParams, info *gofakeit.Info) (interface{}, error) {

			start, err := info.GetString(m, "start")
			if err != nil {
				return nil, err
			}
			start_t, err := time.Parse("2006-01-02", start)
			if err != nil {
				return nil, err
			}

			end, err := info.GetString(m, "end")
			if err != nil {
				return nil, err
			}
			end_t, err := time.Parse("2006-01-02", end)
			if err != nil {
				return nil, err
			}

			t := gofakeit.DateRange(start_t, end_t)
			return t, nil
		},
	})
```

**Comment by brianvoe** [comment]
I completely understand the issue. The reason there isnt a lookup for it is because there isnt a good way of knowing what format to parse them in. Glad you figured out a solution

**Comment by scippio** [comment]
> because there isnt a good way of knowing what format to parse them in.

I think it can be taken from "format" tag.

**Comment by brianvoe** [comment]
If i added a format tag it would be in the format of golangs implementation(which isnt a common format). But because gofakeit has command line and an api server and in the future will have more usages that format type wouldnt meld well with other usages outside of just go.

I might in the future add something that can take in "mm/dd/yyyy" and convert it to "01/02/2006"(or whatever the equivalence is). So that it is more useful for people in the future.
