### ISSUE TITLE
Add Errors

### ISSUE THREAD

**Issue by brianvoe** [brianvoe/gofakeit#179]
Add the ability to generate random errors

**Comment by alex-wzm** [comment]
Hi! I'm keen to work on this. What's your intention here?

Thinking out loud:
* return Go `error`s with random yet realistic-ish error messages
* wrap/nest multiple levels of errors 
* optionally format messages with random data/structs using `%+v`?

**Comment by brianvoe** [comment]
Great question! I too have not figured this one out yet either. Originally I was just going to just do simple golang errors but the issue i have is that I know its a golang package but I have a good amount of people that use this as a command line or http server for other languages and wanted to try to think of a more general way of doing errors that anyone can use. A simple approach is to have a good amount of strings that say sentence like they were issues.

Examples:
"Validation Error: First name is required"
"Internal Server Error"
"Database connection lost"

So if we kept them as simple strings then everyone could use them more generally.

Let me know your thoughts and if you still want to tackle this I can assign this to you.

**Comment by brianvoe** [comment]
Sounds good. I look forward to seeing what you come up with

**Comment by brianvoe** [comment]
Hey any update on this?

**Comment by alex-wzm** [comment]
Hey, I've been laser-focused on work so only coming back to this now. I've implemented the concept in PR #220 - let me know what you think!

Here are a few faker methods I'm thinking to include next:

```go
Errorf(format string) error
WrappedError(err error) error

```

Also, in the spirit of this project, I'd love to leverage the existing faker methods to generate messages, rather than relying on defined message data. For example, `HipsterError()` could use `HipsterSetence()` under the hood to return a message like `"Failed to make cold-pressed sustainable pickle"`.


What options/variations of error messages would you like to see?

**Comment by brianvoe** [comment]
All great stuff so far. In regards to the pr I see what you were thinking in regards to returning a struct that fulfill the error interface. My thought was just to return a simple string. If they want to use it as a golang error we can let them do that afterword if they would like. But I think i like the idea of keeping it a simple string. So that way they can use it however they want. Plus external usages like an http server they can get that response as a string. Let me know if that makes sense.

The only other thing to think about is coming up with as many variations of error messages as possible.
```go
package data

var Error = map[string][]string{
	"message": {
              // Great! But maybe randomize "First name"
              // Example: "Validation Error: {bs /*or*/ buzzword} is required"
              "Validation Error: First name is required", 
              "Internal Server Error", // Great!!!
              "Database connection lost" // Great!!!
         },
}
```

After simply looking at the current list I was thinking about consistency. I use "Validation Error: something wrong" for work but for gofakeit it may make more sense to not have a ":" separator based errors so they are structurally the same. But I think we can still do general message "Validation Error" as one of the options. And if we want we can do various random sub strings of "{randomvalue} is required" or "{randomvalue} must be between {number} and {number}" etc...

Let me know your thoughts.

**Comment by alex-wzm** [comment]
Aha! I think I'm finally catching on... the intention is more about returning error-like content than error types.

I'll add a bunch of strings to the errors data source for you to review. I'll group them into several categories that we can create methods around (e.g. database, input, http, grpc, runtime). And I will randomize parts as advised to maximize the variety of output.

I do think this is a good opportunity to return fake Go errors. I see what you're saying about the ease of returning strings for use cases such http servers and want to propose alternatives.

Option A
As you stated, all our methods return strings and users can construct error types if they want.

Option B
All methods return error types and users can use the `.Error()` method to access the string.

Personally I like option B because I mainly use this library to fake data in unit and integration tests so the error type is one less step for me to implement. And also it feels quite idiomatic to Go... though maybe I'm just over-engineering 😅

I'll defer the decision to you, the author. I just thought I'd give my perspective 🙂

**Comment by brianvoe** [comment]
I hear ya. Im conflicted too. I want to be able to generate on a struct of type error. Lets do option B. The gofakeit api will just handle those differently.

**Comment by brianvoe** [comment]
v6.20.0
