### ISSUE TITLE
gofakeit.Int64() < 0

### ISSUE THREAD

**Issue by xuhaowang** [brianvoe/gofakeit#180]
Why gofakeit.Int64() is always less than 0?

**Comment by brianvoe** [comment]
I cant believe no one has ever pointed this out to me before!!! Looks like it doesnt work with my current usage of int range. I couldnt find anything on the internet about how to do it on such a large number. If you have a good solution for this please let me know. Otherwise ill try to see what i can do about figuring this out.

**Comment by brianvoe** [comment]
I figured it out. I created a new randIntRange function that is capable of generating int at the min and max of int64 capability size. Will go out in the next release

**Comment by brianvoe** [comment]
Fixed v6.10.0
