### ISSUE TITLE
Custom function doesn't support net.IP type

### ISSUE THREAD

**Issue by maheshagrawal2** [brianvoe/gofakeit#202]
I was trying to fake data for type net.IP (go net package) and hence created and registered below custom function.
```
package main

import (
	"fmt"
	"math/rand"
	"net"

	"github.com/brianvoe/gofakeit/v6"
)

type Foo struct {
	IPString string `fake:"{ip}"`    // working
	IP       net.IP `fake:"{ip}"`    // <nil>
}

func main() {
	var f Foo
	gofakeit.AddFuncLookup("ip", gofakeit.Info{
		Category:    "custom",
		Description: "Random IPv4 Address of type net.IP",
		Example:     "1.1.1.1",
		Output:      "net.IP",
		Generate: func(r *rand.Rand, m *gofakeit.MapParams, info *gofakeit.Info) (interface{}, error) {
			data := net.IPv4(byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
			fmt.Printf("data: %s - %T\n", data, data)
			return data, nil
		},
	})
	gofakeit.Struct(&f)
	fmt.Printf("%s - %T\n", f.IPString, f.IPString)
	fmt.Printf("%s - %T", f.IP, f.IP)                         // <nil>
}

```

Custom handler function defined above returns interface{} type but somehow it is just able to return string data type and doesn't work for  net.IP type.

**Comment by brianvoe** [comment]
I understand the issue. I havent figured out a way to make that work at the moment. But i am looking for people that can help with that part. If you cant think of a solution I am open to prs.

**Comment by akutschera** [comment]
When I look at the error code of the ```gofakeit.Struct(&f)``` it shows that there is a parse error ```strconv.ParseUint: parsing "148.117.153.96": invalid syntax``` This is because the net.IP type is actually a byte array which makes gofakeit populate the byte array by calling the custom function for each member of the slice. Since the custom function returns a net.IP (= []byte) instead of a single byte, we get the parse error.
I tried a hack that checks the reflect.Name() of the field. The result is the custom type ("IP") when you are using that instead of the byte array. If that is the case and if you have a custom method defined, I will return the result of the custom function instead of populating a slice with some random values.
Feel free to merge it or rewrite it.

**Comment by brianvoe** [comment]
I made some updates but i think in general what you found makes sense. v6.17.0
