### ISSUE TITLE
male female first name categorization, gender

### ISSUE THREAD

**Issue by dhartford** [brianvoe/gofakeit#216]
Although some people may prefer the 'full' randomization of first name with any gender in these modern times,  sometimes when working with randomized data (particularly for demo/presentation of a solution) it would avoid unnecessary questions if the first name and gender were more aligned when those usecases matter to support focus on a solution rather than the randomized data.

jack : male
jill : female

This could be as simple as randomizing the gender, then passing it as an additional parameter to the first name randomizer, or pairing them in a Person struct generator for scenarios where that use case matters.

**Comment by brianvoe** [comment]
I completely understand where you are coming from. It all comes down to the data. In order to get more "realistic looking" data I would need to start breaking names down by gender, which would make using it a little slower. Im not against it but it really hasn't been an issue with gofakeit considering most usages are just to fill out random data that isnt just lorem ipsum text. Plus gender specific stuff isnt really something I want to be involved in at the moment. But thank you for your feedback I really appreciate it.
