### ISSUE TITLE
Struct method almost doesn't do anything

### ISSUE THREAD

**Issue by toby3d** [brianvoe/gofakeit#65]
It seems that the `Struct` method does not fill out the structure fields at all, except for those that have a `person.first` and `person.last`. I expected that with this method I could fill the structure using the names of the functions available in the package.

## Example
```go
package model_test

import (
	"testing"
	"time"

	"github.com/brianvoe/gofakeit/v4"
	"github.com/stretchr/testify/assert"
)

type User struct {
	Name                string `fake:"{name}"`
	PersonName          string `fake:"{person.name}"`
	PersonFirstLastName string `fake:"{person.first} {person.last}"`
	Email               string `fake:"{email}"`
	ContactEmail        string `fake:"{contact.email}"`
	PersonContactEmail  string `fake:"{person.contact.email}"`
}

func TestFake(t *testing.T) {
	u := new(User)

	gofakeit.Seed(time.Now().UnixNano())
	gofakeit.Struct(u)

	assert.NotEmpty(t, u.Name)                // fail
	assert.NotEmpty(t, u.PersonName)          // fail
	assert.NotEmpty(t, u.PersonFirstLastName) // success
	assert.NotEmpty(t, u.Email)               // fail
	assert.NotEmpty(t, u.ContactEmail)        // fail
	assert.NotEmpty(t, u.PersonContactEmail)  // fail
}
```

**Comment by brianvoe** [comment]
I understand where your coming from. The struct usage is Very simple. If it doesnt have a fake tag then it will just fill out based upon the type. If it does have a fake tag it will pass in that value to the Generate function and do its best to replace what it can for available data sets. So the reason something like {person.first} works is because it exists on the data set.

https://github.com/brianvoe/gofakeit/blob/master/struct.go
https://github.com/brianvoe/gofakeit/blob/master/data/data.go
https://github.com/brianvoe/gofakeit/blob/master/data/person.go
